/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hoaxcelldestop;

/**
 *
 * @author USER
 */
public class dasbord extends javax.swing.JPanel {

    /**
     * Creates new form dasbord
     */
    public dasbord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        KontakKami = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        InfoSaldo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CekData = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BeliPaketan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BeliPulsa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setText("THE HOAX CELL");
        add(jLabel16);
        jLabel16.setBounds(140, 0, 400, 100);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoaxcelldestop/lo.png"))); // NOI18N
        add(jLabel15);
        jLabel15.setBounds(20, 0, 110, 100);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoaxcelldestop/tras1.png"))); // NOI18N
        add(jLabel14);
        jLabel14.setBounds(0, 0, 1030, 100);

        Logout.setBackground(new java.awt.Color(102, 102, 102));
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("LOGOUT");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoaxcelldestop/logout.png"))); // NOI18N
        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout LogoutLayout = new javax.swing.GroupLayout(Logout);
        Logout.setLayout(LogoutLayout);
        LogoutLayout.setHorizontalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutLayout.createSequentialGroup()
                .addGroup(LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogoutLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LogoutLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel12)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        LogoutLayout.setVerticalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(Logout);
        Logout.setBounds(720, 410, 190, 200);

        KontakKami.setBackground(new java.awt.Color(102, 102, 102));
        KontakKami.setForeground(new java.awt.Color(255, 255, 255));
        KontakKami.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Kontak Kami");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoaxcelldestop/book.png"))); // NOI18N

        javax.swing.GroupLayout KontakKamiLayout = new javax.swing.GroupLayout(KontakKami);
        KontakKami.setLayout(KontakKamiLayout);
        KontakKamiLayout.setHorizontalGroup(
            KontakKamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KontakKamiLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(KontakKamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        KontakKamiLayout.setVerticalGroup(
            KontakKamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KontakKamiLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(KontakKami);
        KontakKami.setBounds(420, 410, 190, 200);

        InfoSaldo.setBackground(new java.awt.Color(102, 102, 102));
        InfoSaldo.setForeground(new java.awt.Color(255, 255, 255));
        InfoSaldo.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Info Saldo");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoaxcelldestop/risk.png"))); // NOI18N

        javax.swing.GroupLayout InfoSaldoLayout = new javax.swing.GroupLayout(InfoSaldo);
        InfoSaldo.setLayout(InfoSaldoLayout);
        InfoSaldoLayout.setHorizontalGroup(
            InfoSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoSaldoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(InfoSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        InfoSaldoLayout.setVerticalGroup(
            InfoSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoSaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        add(InfoSaldo);
        InfoSaldo.setBounds(100, 410, 190, 200);

        CekData.setBackground(new java.awt.Color(102, 102, 102));
        CekData.setForeground(new java.awt.Color(255, 255, 255));
        CekData.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cek Data");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoaxcelldestop/earth-globe.png"))); // NOI18N

        javax.swing.GroupLayout CekDataLayout = new javax.swing.GroupLayout(CekData);
        CekData.setLayout(CekDataLayout);
        CekDataLayout.setHorizontalGroup(
            CekDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CekDataLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(CekDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CekDataLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        CekDataLayout.setVerticalGroup(
            CekDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CekDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        add(CekData);
        CekData.setBounds(720, 150, 190, 201);

        BeliPaketan.setBackground(new java.awt.Color(102, 102, 102));
        BeliPaketan.setForeground(new java.awt.Color(255, 255, 255));
        BeliPaketan.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Beli Paketan");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoaxcelldestop/telegram.png"))); // NOI18N

        javax.swing.GroupLayout BeliPaketanLayout = new javax.swing.GroupLayout(BeliPaketan);
        BeliPaketan.setLayout(BeliPaketanLayout);
        BeliPaketanLayout.setHorizontalGroup(
            BeliPaketanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BeliPaketanLayout.createSequentialGroup()
                .addGroup(BeliPaketanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BeliPaketanLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BeliPaketanLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BeliPaketanLayout.setVerticalGroup(
            BeliPaketanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BeliPaketanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        add(BeliPaketan);
        BeliPaketan.setBounds(420, 150, 190, 200);

        BeliPulsa.setBackground(new java.awt.Color(102, 102, 102));
        BeliPulsa.setForeground(new java.awt.Color(255, 255, 255));
        BeliPulsa.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Beli Pulsa");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoaxcelldestop/chat.png"))); // NOI18N

        javax.swing.GroupLayout BeliPulsaLayout = new javax.swing.GroupLayout(BeliPulsa);
        BeliPulsa.setLayout(BeliPulsaLayout);
        BeliPulsaLayout.setHorizontalGroup(
            BeliPulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BeliPulsaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(BeliPulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        BeliPulsaLayout.setVerticalGroup(
            BeliPulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BeliPulsaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        add(BeliPulsa);
        BeliPulsa.setBounds(100, 150, 190, 200);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoaxcelldestop/gambar1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, -230, 1110, 1230);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BeliPaketan;
    private javax.swing.JPanel BeliPulsa;
    private javax.swing.JPanel CekData;
    private javax.swing.JPanel InfoSaldo;
    private javax.swing.JPanel KontakKami;
    private javax.swing.JPanel Logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
