/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hoaxcelldestop;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static java.lang.Math.random;
import java.util.Random;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class layoutHoax extends javax.swing.JFrame {
    DefaultTableModel model;
    private String tgl;
    Random rand = new Random();
    int R = rand.nextInt(1000);
    int F = rand.nextInt(1000);

    /**
     * Creates new form layoutHoax
     */
    public layoutHoax() throws SQLException {
        initComponents();
        String [] field = {"id_transaksi", "operator", "nominal", "harga_jual", "tanggal", "no_telepon"};
        model = new DefaultTableModel(field, 0);
        tabelhistori.setModel(model);
        tampilkan();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textid1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelhistori = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        texthargajual = new javax.swing.JTextField();
        inputnominal = new javax.swing.JComboBox<>();
        inputoperator = new javax.swing.JComboBox<>();
        textnotelp = new javax.swing.JTextField();
        textid = new javax.swing.JTextField();
        random = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1028, 653));
        getContentPane().setLayout(null);

        textid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textid1ActionPerformed(evt);
            }
        });
        getContentPane().add(textid1);
        textid1.setBounds(170, 150, 140, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("ID ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 150, 130, 30);

        tanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalPropertyChange(evt);
            }
        });
        getContentPane().add(tanggal);
        tanggal.setBounds(170, 400, 140, 30);

        tabelhistori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Id_Transaksi", "Operator", "Nominal", "Harga Jual", "TGL Trans", "No Telepon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelhistori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelhistoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelhistori);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(350, 150, 630, 360);

        tambah.setBackground(new java.awt.Color(0, 153, 0));
        tambah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 255));
        tambah.setText("Tambahkan");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(170, 520, 140, 40);
        getContentPane().add(texthargajual);
        texthargajual.setBounds(170, 350, 140, 30);

        inputnominal.setBackground(new java.awt.Color(0, 153, 255));
        inputnominal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5000", "10000", "25000", "50000", "100000" }));
        inputnominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputnominalActionPerformed(evt);
            }
        });
        getContentPane().add(inputnominal);
        inputnominal.setBounds(170, 300, 140, 30);

        inputoperator.setBackground(new java.awt.Color(0, 153, 255));
        inputoperator.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N
        inputoperator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Telkomsel", "Indosat", "XL", "Axis", "Tri", "Smartfren", " " }));
        getContentPane().add(inputoperator);
        inputoperator.setBounds(170, 250, 140, 30);
        getContentPane().add(textnotelp);
        textnotelp.setBounds(170, 450, 140, 30);

        textid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidActionPerformed(evt);
            }
        });
        getContentPane().add(textid);
        textid.setBounds(170, 200, 90, 30);

        random.setText("R");
        random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomActionPerformed(evt);
            }
        });
        getContentPane().add(random);
        random.setBounds(270, 200, 40, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Harga Jual");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 350, 100, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Nominal");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 300, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Operator");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 250, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("TGL Transaksi");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 400, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("No Telpon");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 450, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("ID Transaksi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 200, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("THE HOAX CELL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 0, 400, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoaxcelldestop/lo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 0, 100, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoaxcelldestop/tras1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1030, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoaxcelldestop/gambar1.jpg"))); // NOI18N
        jLabel1.setText("Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1040, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelhistoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelhistoriMouseClicked
        int a = tabelhistori.getSelectedRow();
        if (a > -1){
            textid.setText(model.getValueAt(a, 0).toString());
            inputoperator.setSelectedItem(model.getValueAt(a, 1).toString());
            inputnominal.setSelectedItem(model.getValueAt(a, 2).toString());
            texthargajual.setText(model.getValueAt(a, 3).toString());
            tanggal.setDate(null);
            textnotelp.setText(model.getValueAt(a, 5).toString());
    
        }
    }//GEN-LAST:event_tabelhistoriMouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        rand = new Random();
        int R = rand.nextInt(50);
        try {
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/data","root","");
            koneksi.createStatement().executeUpdate("INSERT INTO transaksi VALUES ('"+textid.getText()+"','"+tgl+"')");
            koneksi.createStatement().executeUpdate("INSERT INTO detail_transaksi (id, id_transaksi, operator, nominal, harga_jual, no_telepon) VALUES ('"+textid.getText()+"','"+inputoperator.getSelectedItem()+"','"+inputnominal.getSelectedItem()+"','"+texthargajual.getText()+"','"+textnotelp.getText()+"')");
                            tampilkan();
                            reset();
        } catch (SQLException ex) {
            Logger.getLogger(layoutHoax.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void tanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalPropertyChange
        if(tanggal.getDate() != null){
            SimpleDateFormat format_tanggal = new SimpleDateFormat("yyyy-MM-dd");
            tgl = format_tanggal.format(tanggal.getDate());
        }
    }//GEN-LAST:event_tanggalPropertyChange

    private void inputnominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputnominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputnominalActionPerformed

    private void textidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidActionPerformed
        // TODO add your handling code here:
        textid.setText(""+R);
    }//GEN-LAST:event_textidActionPerformed

    private void randomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomActionPerformed
        // TODO add your handling code here:
        textid.setText(""+R);
    }//GEN-LAST:event_randomActionPerformed

    private void textid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textid1ActionPerformed

    private Connection koneksi;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(layoutHoax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(layoutHoax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(layoutHoax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(layoutHoax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new layoutHoax().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(layoutHoax.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> inputnominal;
    private javax.swing.JComboBox<String> inputoperator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton random;
    private javax.swing.JTable tabelhistori;
    private javax.swing.JButton tambah;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTextField texthargajual;
    private javax.swing.JTextField textid;
    private javax.swing.JTextField textid1;
    private javax.swing.JTextField textnotelp;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
        try {
            int row = tabelhistori.getRowCount();
            for (int i = 0; i < row ; i++){
                model.removeRow(0);
            }
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/data","root","");
            ResultSet rs = koneksi.createStatement().executeQuery("SELECT detail_transaksi.id, transaksi.id_transaksi, detail_transaksi.operator, detail_transaksi.nominal, detail_transaksi.harga_jual, transaksi.tanggal, detail_transaksi.no_telepon FROM transaksi, detail_transaksi WHERE transaksi.id_transaksi=detail_transaksi.id_transaksi");
            while (rs.next()){
                String [] data = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)};
                model.addRow(data);
            }} catch (SQLException ex) {
            Logger.getLogger(layoutHoax.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void reset() {
        textid.setText("");
        inputoperator.setSelectedItem("");
        inputnominal.setSelectedItem("");
        texthargajual.setText("");
        tanggal.setDateFormatString("");
        textnotelp.setText("");
        
    }
    
}
